### ISSUE TITLE
Correct use with mapPropsToFields and getFieldDecorator?

### ISSUE THREAD

**Issue by JeffJankowski** [antoniopresto/antd-mask-input#1]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[x] question about how to use this project

* **Summary**

Is is possible to use this component with `Form.getFieldDecorator()`? As a drop-in replacement to `<Input />`, the `value` is getting overwritten with the following warning in the console:

> Warning: `getFieldDecorator` will override `value`, so please don't set `value` directly and use `setFieldsValue` to set it.

**Comment by antoniopresto** [comment]
Thank you for reporting. I have not yet used with `getFieldDecorator`;
Is it just a warning or does it not work?

**Comment by JeffJankowski** [comment]
It did not work at all, unfortunately. I'm now using `react-text-mask` and rendering the antd `Input` as a custom component, which is working sufficiently.

**Comment by astrikov-d** [comment]
@JeffJankowski, I'm experiencing same issue with `antd`. Can you please show me an example how you've solved this with `react-text-mask`? Thank you.

**Comment by JeffJankowski** [comment]
@astrikov-d, I learned on a random thread that I needed to grab the inner `input` element for the reference to bind correctly.

```
<MaskedInput
  render={(ref, passedProps: Props) => (
    <Input
      value={value}
      ref={input => input && ref(input.input)}
      {...passedProps}
    />
  )}
/>;
```

**Comment by maksaimer** [comment]
I have the same problem with `getFieldDecorator`

**Comment by JeffJankowski** [comment]
@maksaimer Before switching to Formik, I got `getFieldDecorator` to work with `react-text-mask` by doing something like:
```
<MaskedInput
  {...props}
  render={(ref, passedProps: Props) => {
    const { field, formUtils, ...otherProps } = passedProps;
    // this is kept in sync with value, and will produce warnings with getFieldDecorator()
    // if the prop is not deleted
    delete otherProps.defaultValue;
    return formUtils.getFieldDecorator(field)(
      <Input ref={input => input && ref(input.input)} {...otherProps} />
    );
  }}
/>
```

**Comment by antoniopresto** [comment]
Sorry for the delay, can you test version 0.1.7. please?
