### ISSUE TITLE
Underscores are making len rule fail

### ISSUE THREAD

**Issue by mfgabriel92** [antoniopresto/antd-mask-input#10]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
The `mask` prop places an underscore on unfilled positions of the mask. When the field is empty, you see them as the field's placeholder, but once you start to type, they'll become actual characters typed in the field. Like this, Antd's `len` rule fails. If I want to set a required size to ensure all the characters of the field (a phone) is filled up, these underscores will count as characters.

```javascript
<Form.Item label="Phone">
  {getFieldDecorator('phone', {
    rules: [
      { required: true, message: 'Phone is mandatory' },
      { len: 15, message: 'Phone must contain all digits' },
    ],
  })(
    <MaskedInput
      mask="(11) 11111-1111"
      id="phone"
      name="phone"
      value={phone}
      onChange={e => setPhone(e.target.value)}
    />
  )}
</Form.Item>
```

but

![Screenshot_2020-01-11_09-45-54](https://user-images.githubusercontent.com/26734503/72204484-35f0e400-3457-11ea-8be4-fd0f61feb42b.png)

In theory, it should display the `len` error message, but due to the underscores taking place, it cannot be done. Any ideas? Perhaps an option to disable the underscores?

**Comment by antoniopresto** [comment]
I think you'll need to change the `placeholderChar` or add a custom validator
