### ISSUE TITLE
Input props to lower case

### ISSUE THREAD

**Issue by rvitorgomes** [antoniopresto/antd-mask-input#11]
* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

![image](https://user-images.githubusercontent.com/14111893/73969696-a70ea480-48fa-11ea-8db9-360594bd98b2.png)

There's any impact on using lowercase on the custom input props?

**Comment by antoniopresto** [comment]
I think we need to remove this prop here: https://github.com/antoniopresto/antd-mask-input/blob/1fd777af7c827297170fd6e6b24d76e25f653f1a/src/lib/MaskedInput.tsx#L233

Can you please send a PR?

**Comment by antoniopresto** [comment]
I just published version 2.0
See examples in tests, readme or storybook: https://github.com/antoniopresto/antd-mask-input/blob/master/stories/input.stories.tsx
