### ISSUE TITLE
How to set mask to element or dynamic mask

### ISSUE THREAD

**Issue by jeffersonmello** [antoniopresto/antd-mask-input#12]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[X] question about how to use this project

* **How to set mask to element or value**

ex: el.SetMaskedInput("(11) 1111-1111"); or 
<MaskedInput mask="(11) 1?1111-1111" name="Telefone" size="default" /> when value before ? its a optional

**Comment by antoniopresto** [comment]
I believe you refer to this: https://github.com/insin/inputmask-core/issues/1
