### ISSUE TITLE
ComponentWillUpdate has been renamed, and is not recommended for use

### ISSUE THREAD

**Issue by JumpAttacker** [antoniopresto/antd-mask-input#16]
* **I'm submitting a ...**
[+] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

![image](https://user-images.githubusercontent.com/10989729/78253018-68612900-74fc-11ea-9c41-d20d74d85c80.png)

**Comment by lucasltv** [comment]
UP

**Comment by temulen0121** [comment]
Is there any solution on this warning?

**Comment by antoniopresto** [comment]
send a PR

**Comment by rolimans** [comment]
Just linked a pull request to fix this
