### ISSUE TITLE
The Input returns incorrect value

### ISSUE THREAD

**Issue by ildarnm** [antoniopresto/antd-mask-input#17]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
*Actually:*
I set the mask "11111-111-1-1111-1111111"
but I can get the value "`1____-___-_-____-_______`" if user inputs only one symbol "1"
*Expect:*
I expect that if I set a mask I will get a value that matches the mask and the change event to be generated only if the value matches the mask.

**Comment by vinceve** [comment]
@ildarnm Or get at least the value without the rest of the mask. So you can throw it through a validator :)

**Comment by antoniopresto** [comment]
I just published version 2.0
See examples in tests, readme or storybook: https://github.com/antoniopresto/antd-mask-input/blob/master/stories/input.stories.tsx
