### ISSUE TITLE
Catch pattern error

### ISSUE THREAD

**Issue by victornikitin** [antoniopresto/antd-mask-input#18]
I get Uncaught Error whet pattern is not Ok.
For example for pattern "+7".
Error message: pattern "+7" does not contain any editable characters.

How to catch it? to prevent Uncaught Error?

**Comment by antoniopresto** [comment]
I just published version 2.0
See examples in tests, readme or storybook: https://github.com/antoniopresto/antd-mask-input/blob/master/stories/input.stories.tsx
