### ISSUE TITLE
Edge & IE 11 spread syntax error

### ISSUE THREAD

**Issue by MichelKansou** [antoniopresto/antd-mask-input#20]
I have an issue with Edge & IE11 is it possible to add babel to convert the spread syntax in your build ?

**Comment by antoniopresto** [comment]
the build is using ES6?

**Comment by antoniopresto** [comment]
I think you are using the module build: https://github.com/antoniopresto/antd-mask-input/blob/dc01312d1fe5a8939462f12d48999bb4783f29b3/package.json#L5-L7

**Comment by MichelKansou** [comment]
I installed the module with npm
``` npm install antd-mask-input --save```
But my final build of my project contain MaskedInput Component and it's not converted to ES2015

**Comment by antoniopresto** [comment]
I just published version 2.0
See examples in tests, readme or storybook: https://github.com/antoniopresto/antd-mask-input/blob/master/stories/input.stories.tsx
