### ISSUE TITLE
Does not handle `readOnly` prop

### ISSUE THREAD

**Issue by lukasluecke** [antoniopresto/antd-mask-input#22]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Setting `readOnly={true}` should prevent changes to the field value, currently it is ignored.

**Comment by prjanja** [comment]
You should use the "disabled" property instead as described in this documentation
https://ant.design/components/input/#Input

**Comment by lukasluecke** [comment]
`disabled` and `readOnly` have different effects though - and I want the `readOnly` behaviour 🙂 It works just fine with normal antd `<Input/>` - the issue is that mask-input intercepts the key-events directly, and therefore does not respect the `readOnly`.

**Comment by antoniopresto** [comment]
I just published version 2.0
See examples in tests, readme or storybook: https://github.com/antoniopresto/antd-mask-input/blob/master/stories/input.stories.tsx
