### ISSUE TITLE
Incorrect initial value for the given mask

### ISSUE THREAD

**Issue by kubade-anup** [antoniopresto/antd-mask-input#23]
* **I'm submitting a ...**
[*] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Here I am trying to use mask for the IP address. Where in each part there could be max 3 digits.
Usage: `<MaskedInput mask="111.111.111.111" value="192.16.1.5" />`
Expectation: The input box should render value "192.16_.1__.5__"
Actual Outcome: And here is what gets rendered "192.16_.1_5.___"

When value is "0.0.0.0" this is what I get "0_0.0_0.___.___"

**Comment by antoniopresto** [comment]
I just published version 2.0
See examples in tests, readme or storybook: https://github.com/antoniopresto/antd-mask-input/blob/master/stories/input.stories.tsx
