### ISSUE TITLE
How to mask IP Address

### ISSUE THREAD

**Issue by kubade-anup** [antoniopresto/antd-mask-input#24]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[*] question about how to use this project

* **Summary**
Can you share an example to mask the IP address. Like "111.111.111.111" where the each part could be at max a 3 digit number.

**Comment by carlosedof** [comment]
any response on this?

**Comment by antoniopresto** [comment]
I just published version 2.0
See examples in tests, readme or storybook: https://github.com/antoniopresto/antd-mask-input/blob/master/stories/input.stories.tsx
