### ISSUE TITLE
How to mask US phone numbers , keeping +1 as constant 

### ISSUE THREAD

**Issue by surajmn1** [antoniopresto/antd-mask-input#26]
* **I'm submitting a ...**

[ ] question about how to use this project

* **Summary**
i want to keep input +1 by default
mask used in input : mask="+\1 (111) 111-1111"
error : Don't use octal: '\1'. Use '\u....' instead    no-octal-escape
if i escape wit \x1 it shows in input as +x1

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by ratnabh-classic** [comment]
hey @surajmn1  did u find any workaround for this ?

**Comment by antoniopresto** [comment]
I just published version 2.0
See examples in tests, readme or storybook: https://github.com/antoniopresto/antd-mask-input/blob/master/stories/input.stories.tsx
