### ISSUE TITLE
How to use dynamic mask?

### ISSUE THREAD

**Issue by jeffersonmello** [antoniopresto/antd-mask-input#29]
its possible use dynamic mask?  Like in the ngx-mask 

`mask="(00) 0000-0000||(00) 0 0000-0000"`

**Comment by m7he4rt** [comment]
progress?

**Comment by antoniopresto** [comment]
in progress: https://github.com/antoniopresto/antd-mask-input/tree/feature/use-imask

**Comment by m7he4rt** [comment]
thanks for support

**Comment by antoniopresto** [comment]
I just published version 2.0
See examples in tests, readme or storybook: https://github.com/antoniopresto/antd-mask-input/blob/master/stories/input.stories.tsx

**Comment by m7he4rt** [comment]
ok, thank you for your support!
