### ISSUE TITLE
The onPast event does not work at all

### ISSUE THREAD

**Issue by SHUANESH** [antoniopresto/antd-mask-input#38]
* **I'm submitting a ...**
[ ] bug report
* **Summary**

Hi, in my project I want to allow the user to enter in the field cell phone numbers that he copied and paste into the field but it is not possible at all, can anyone help me with this problem? 

Thanks :)

**Comment by antoniopresto** [comment]
I just published version 2.0
See examples in tests, readme or storybook: https://github.com/antoniopresto/antd-mask-input/blob/master/stories/input.stories.tsx
