### ISSUE TITLE
component is not rendering

### ISSUE THREAD

**Issue by niltonxp2** [antoniopresto/antd-mask-input#39]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
```js
r.state._Input.setState is not a function
```
![image](https://user-images.githubusercontent.com/88057912/157503136-4710bc56-0ddb-4497-a30d-4b3a6e3ceab3.png)

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
node 14.17.0
react: 17.02
"react-scripts": "4.0.3"

**Comment by leehk-hwik** [comment]
I'm looking for the cause of the same problem.
The conclusion I made is presumed to arise from the change of the dependent library

If you force the version in package.json, there is no error.

Before
```json
  "dependencies": {
    "antd": "^4.16.5"
}

```

After
```json
  "dependencies": {
    "antd": "4.16.5"
}
```

**Comment by EatBears** [comment]
@niltonxp2 how did you fix that?)
