### ISSUE TITLE
Failed to parse source map from /node_modules/antd-mask-input/src/lib/MaskedInput.tsx

### ISSUE THREAD

**Issue by sekizlipenguen** [antoniopresto/antd-mask-input#40]
* **I'm submitting a ...**
[* ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

WARNING in ./node_modules/antd-mask-input/build/module/lib/MaskedInput.js
Module Warning (from ./node_modules/react-scripts/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/node_modules/antd-mask-input/src/lib/MaskedInput.tsx' file: Error: ENOENT: no such file or directory, open 'node_modules/antd-mask-input/src/lib/MaskedInput.tsx'

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

**Comment by sekizlipenguen** [comment]
++

![Screen Shot 2022-03-08 at 15 53 22](https://user-images.githubusercontent.com/36849861/157637256-ea6c115a-69e5-468c-89cd-093b0c74ee9a.png)

**Comment by VjIntesols** [comment]
+ 1

**Comment by sekizlipenguen** [comment]
for workaround you should try this version: "antd": "4.18.9"

**Comment by pablohenriqueop** [comment]
> for workaround you should try this version: "antd": "4.18.9"

i tryed it but don't works :/

**Comment by sekizlipenguen** [comment]
> > for workaround you should try this version: "antd": "4.18.9"
> 
> i tryed it but don't works :/

must make sure that the version you have installed is correct.

1. delete this folder and reload: node_modules (terminal -> project folder -> rm -rf node_modules/)
2. yarn install 
3. use exact expression for version ( ^ remove )


![Screen Shot 2022-03-12 at 16 47 29](https://user-images.githubusercontent.com/36849861/158020531-2082b612-0eb7-4fe8-8820-69c485a87d4a.png)

**Comment by pablohenriqueop** [comment]
> > > for workaround you should try this version: "antd": "4.18.9"
> > 
> > 
> > i tryed it but don't works :/
> 
> must make sure that the version you have installed is correct.
> 
> 1. delete this folder and reload: node_modules (terminal -> project folder -> rm -rf node_modules/)
> 2. yarn install
> 3. use exact expression for version ( ^ remove )
> 
> ![Screen Shot 2022-03-12 at 16 47 29](https://user-images.githubusercontent.com/36849861/158020531-2082b612-0eb7-4fe8-8820-69c485a87d4a.png)

It works. Thanks!

**Comment by antoniopresto** [comment]
I just published version 2.0
See examples in tests, readme or storybook: https://github.com/antoniopresto/antd-mask-input/blob/master/stories/input.stories.tsx
