### ISSUE TITLE
Internal value of the input doesn't get refreshed when a new value is received in props

### ISSUE THREAD

**Issue by alesn** [antoniopresto/antd-mask-input#43]
* **I'm submitting a ...**
[x] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Hi, I am using version 2.0.5 of antd-mask-input. In other cases it seems to work fine but when the component (MaskedInput) receives a new - changed value in the 'value' prop (from one it had been instantiated with before) after user already typed something in the field, the new value doesn't get updated in the component. The old value the user typed keeps being displayed in the input field though a different value has been passed in props already. imask package also logs a warning in the console: Element value was changed outside of mask. Syncronize mask using `mask.updateValue()` to work properly.
I don't see that imask.current from antd-mask-input would be made accessible from outside of the package. Hopefully this problem can get resolved and antd-mask-input can work without having to call mask.updateValue() from outside of the package.
Having read this problem description, can you think of something that could be wrong there?

**Comment by antoniopresto** [comment]
Thanks for reporting. Can you please send a reproduction example or just clone this repo and add a use case in this file https://github.com/antoniopresto/antd-mask-input/blob/master/stories/input.stories.tsx
