### ISSUE TITLE
I'm not able to install version v.2.0.6

### ISSUE THREAD

**Issue by m7he4rt** [antoniopresto/antd-mask-input#45]
* **I'm submitting a ...**
[X] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Version 2.0.6 does not build files in the node_modules folder but 2.0.5 has built files in node_modules

v2.0.5
![image](https://user-images.githubusercontent.com/44484286/160974789-5cd0201f-ac6c-4704-8e42-d6e64241f7b5.png)

v2.0.6
![image](https://user-images.githubusercontent.com/44484286/160975009-35449401-387d-4892-ae8b-f05b2e90cbdf.png)

**Comment by antoniopresto** [comment]
Fixed in 2.0.7
Thanks for reporting.
