### ISSUE TITLE
Update code to support setFieldsValue from Form object.

### ISSUE THREAD

**Issue by JoaoZanetti** [antoniopresto/antd-mask-input#46]
* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* When I try to use the [setFieldsValue](https://ant.design/components/form/?theme=dark#API#Form.Provider) function from Form object fields don't get populated.

*
<img width="235" alt="PastedGraphic-2" src="https://user-images.githubusercontent.com/18476803/161081301-df56bacd-c680-437d-9f6c-01273d50f1e6.png">
<img width="669" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/18476803/161081332-d8bbf203-1d3d-49e7-a59c-f6c80a5e4c5c.png">
<img width="528" alt="PastedGraphic-3" src="https://user-images.githubusercontent.com/18476803/161081359-cde6d6c4-6979-466c-ac0b-892a7d42a0b7.png">

**Comment by antoniopresto** [comment]
Can't reproduce.  This example is working:

```ts
   const [form] = Form.useForm();

  React.useEffect(() => {
    const interval = setInterval(() => {
      form.setFieldsValue({phone: `${Math.random()*1000}`})
    }, 700);

    return () => clearInterval(interval)
  }, [])

  return <Form form={form}>
    <Form.Item
      label="Phone"
      name="phone"
      initialValue={'11'}
    >
      <DynamicPhone />
    </Form.Item>
  </Form>
```

I would recommend you to check your antd version or log `Object.keys(newObj)` 

> The version 2.0.0 Requires antd >= 4.19.0 - for previous versions use the version 0.1.15
