### ISSUE TITLE
MaskedInput not highlighted in red when form validation failed

### ISSUE THREAD

**Issue by CatherineShemenkova** [antoniopresto/antd-mask-input#59]
* **I'm submitting a ...**
[+] bug report

* **Summary**
I create MaskedInput with such mask:

`const mask = useMemo(
    () => [
      {
        mask: Number,
        scale: 2,
        thousandsSeparator: ' ',
        radix: '.',
        normalizeZeros: false,
        min: 0,
        max: 9999.99,
      },
    ],
    []
  );`
  
And insert it in ant Form.Item with `required` prop.
When validation failed nothing happens with MaskedInput (borders not red, focus state not red etc).

I can provide status only manually, but I cant know about it (through props input status not provided). 

antd version: 4.22.5
antd-mask-input version: 2.0.7

**Comment by renerlemes** [comment]
@CatherineShemenkova how to solve this? I have the same problem.

**Comment by CatherineShemenkova** [comment]
> @CatherineShemenkova how to solve this? I have the same problem.

I' m afraid I still don' t know. I used react-number-format instead.
