### ISSUE TITLE
Static characters not getting skipped on mobile

### ISSUE THREAD

**Issue by anbarasiu** [antoniopresto/antd-mask-input#6]
This is a bug report.

The static characters get skipped on a masked input field, on desktop, but not on the mobile browser. 
For example, for the format 'DD-MM-YYYY', the masking pattern is '11-11-1111', and after entering 'DD', the cursor skips the '-' and automatically moves to the 'MM' part, on the desktop browser.  But, on the mobile, the cursor doesn't skip the static '-', hence the input character is lost and confuses the user.

**Comment by antoniopresto** [comment]
What mobile device and browser?

**Comment by anbarasiu** [comment]
I noticed this on Chrome on all Android devices.

**Comment by antoniopresto** [comment]
Related to https://github.com/insin/react-maskedinput/issues/126
Submitting a fix. 
TODO send a PR to react-maskedinput

**Comment by ariunbatb** [comment]
Still not working on mobile
