### ISSUE TITLE
MaskedInput Component not working on internet explorer 11.

### ISSUE THREAD

**Issue by coskunuyar** [antoniopresto/antd-mask-input#7]
The component works properly on chrome but on ie11 it causes an error.

**"Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.**"

**Comment by antoniopresto** [comment]
Thank you for submitting. I have no access to IE right now, can you help debugging this?
For now, just check if this helps you: https://ant.design/docs/react/getting-started#Compatibility

**Comment by SercanBozkurt** [comment]
Merhaba,
Dediğiniz yolu denedim fakat olmadı. Bunu başka bir yolu varmıdır.

**Comment by rvitorgomes** [comment]
@coskunuyar  @SercanBozkurt 

I've been using it on IE 11 and no problems so far. Can you help with more information to reproduction?

**Comment by SercanBozkurt** [comment]
@rvitorgomes 
I solved this issue with a different method.
Fixed issue using https://www.npmjs.com/package/react-input-mask. For example, you can review https://github.com/ant-design/ant-design/issues/10580 this page.

**Comment by coskunuyar** [comment]
I guess issue is not about the component most probably about the things we do in our projects conflicts with logic of masking.Sorry for inconvenience am closing this issue.
