### ISSUE TITLE
Pass the maxLength prop to the wrapped input component

### ISSUE THREAD

**Issue by smilledge** [antoniopresto/antd-mask-input#8]
* **I'm submitting a ...**
[ ] bug report
[x] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

The `maxLength` prop should be passed to the wrapped `<Input />` component if explicitly set. Currently it is being overridden with the length of the pattern string. 

* **Other information**

For example, a card CVV can be a 3 or 4 digit number. As they are usually only 3 digits it makes sense to show a pattern that matches this. However, the user should still be able to enter 4 digits. 

```
<MaskedInput mask="111" maxLength={4} />
```

**Comment by antoniopresto** [comment]
I think you [need this feature](https://github.com/insin/inputmask-core/issues/1)

**Comment by smilledge** [comment]
Yep, you're right 😉
